routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', 'PagesController@home');
Route::resource('inertia', 'InertiaController');

app/Inertia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Inertia extends Model
{
    //
    protected $fillable = [
        'sku', 'upc', 'artist', 'title', 'format', 'release_date', 'price', 'status', 'stock', 'extra_info'
    ];

    public function scopeSearch($query, $q) 
    {
        if($q == null) return $query;
        return $query
                    ->where('sku', 'LIKE', "%{$q}%")
                    ->orWhere('upc', 'LIKE', "%{$q}%")
                    ->orWhere('artist', 'LIKE', "%{$q}%")
                    ->orWhere('title', 'LIKE', "%{$q}%");
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/InertiaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Inertia;
use Config;
use Maatwebsite\Excel\Facades\Excel;

class InertiaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index( Request $request)
    {
        $sortBy = 'id';
        $orderBy = 'desc';
        $perPage = 50;
        $q = null;

        if ($request->has('orderBy')) $orderBy = $request->query('orderBy');
        if ($request->has('sortBy')) $sortBy = $request->query('sortBy');
        if ($request->has('perPage')) $perPage = $request->query('perPage');
        if ($request->has('q')) $q = $request->query('q');

        if( $sortBy && $orderBy) {
            $items = Inertia::search($q)->orderBy($sortBy, $orderBy)->paginate($perPage);
            $links = $items->appends(['q' => $q, 'sortBy' => $sortBy, 'orderBy' => $orderBy])->links();
        } else {
            $items = Inertia::paginate($perPage);
            $links = '';
        }
        
        //Excel::import(new \App\Imports\InertiaImport, 'Inertia03042019.xls');
        // $items = Inertia::search($q)->orderBy($sortBy, $orderBy)->paginate($perPage);
        return view('inertia', compact('items', 'orderBy', 'sortBy', 'q', 'perPage'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        
        //echo 'store';
        $file = $request->file('inertiafile');
        //$destinationPath = 'uploads';
        //$file->move($destinationPath,$file->getClientOriginalName());
        Excel::import(new \App\Imports\InertiaImport, request()->file('inertiafile'));

        
        return redirect('/inertia');
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function inertiaupload() 
    {
        return 'inertiaupload';
    }
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PagesController extends Controller
{
    //
    public function home() {
        return view('home');
    }
}

resources/views/home.blade.php
@extends('layout.base')

@section('title', 'SmartTimes Stock Manager')

@section('content')
    
    <div class="content is-medium">
        <h3>Hello</h3>
        <p class="subtitle">Just a quick way to manage stock</p>
    </div>
@endsection

resources/views/inertia.blade.php
@extends('layout.base')

@section('title', 'INERTIA - SmartTimes Stock Manager')

@section('content')
    <div class="content">
        <form action="/inertia" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="field  is-grouped">
                <div class="file">
                    <label class="file-label">
                        <input class="file-input" type="file" name="inertiafile">
                        <span class="file-cta">
                        <span class="file-icon">
                            <i class="fas fa-upload"></i>
                        </span>
                        <span class="file-label">
                            Upload the latest stock sheet:
                        </span>
                        </span>
                    </label>
                </div>
                <div class="control">
                    <input type="submit" class="button is-link" value="Upload" />
                </div>
            </div>
        </form>
    </div>

    <div class="content">
        <form action="{{ route('inertia.index') }}">
            <div class="field is-grouped">
                <div class="control is-expanded">
                    <input class="input" type="search" name="q" value="{{ $q }}">
                </div>
            
                <div class="control">
                    <div class="select">
                        <select name="sortBy" class="form-control form-control-sm" value="{{ $sortBy }}">
                            @foreach(['id', 'status', 'stock'] as $col)
                            <option @if($col == $sortBy) selected @endif value="{{ $col }}">{{ ucfirst($col) }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            
                <div class="control">
                    <div class="select">
                        <select name="orderBy" class="form-control form-control-sm" value="{{ $orderBy }}">
                            @foreach(['asc', 'desc'] as $order)
                            <option @if($order == $orderBy) selected @endif value="{{ $order }}">{{ ucfirst($order) }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            
                <div class="control">
                    <div class="select">
                        <select name="perPage" class="form-control form-control-sm" value="{{ $perPage }}">
                            @foreach(['50','100','250','500'] as $page)
                            <option @if($page == $perPage) selected @endif value="{{ $page }}">{{ $page }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            
                <div class="control">
                <button type="submit" class="button is-primary"">Filter</button>
                </div>
            </div>
        </form>
    </div>
        
    <div class="content is-small">
        <table class="table is-striped is-fullwidth">
            <thead>
                <tr>
                    <th>State</th>
                    <th>sku</th>
                    <th>upc</th>
                    <th>artist</th>
                    <th>title</th>
                    <th>format</th>
                    <th>release_date</th>
                    <th>price</th>
                    <th>status</th>
                    <th>stock</th>
                    <th>Is in ST [Last Updated]</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($items as $item)
                    <tr {{ $item->state_changed ? 'class=is-selected' : '' }}>
                        <th>
                            @switch($item->state_changed)
                                @case(0)
                                    Changed
                                    @break
                                @case(2)
                                    Changed & Updated
                                    @break
                                @default
                                    No Changes
                            @endswitch
                        </th>
                        <td>{{ $item->sku }}</td>
                        <td>{{ $item->upc }}</td>
                        <td>{{ $item->artist }}</td>
                        <td>{{ $item->title }}</td>
                        <td>{{ $item->format }}</td>
                        <td>{{ $item->release_date }}</td>
                        <td>{{ $item->price }}</td>
                        <td>{{ $item->status }}</td>
                        <td>{{ $item->stock }}</td>
                        <td>{{ $item->is_in_smarttimes ? 'Yes ['. $item->updated_smarttimes_on .']' : 'No' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    {{ $items->links() }}
@endsection

resources/views/layout/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

</head>
<body>
    
    <section class="hero is-primary">
        <div class="hero-head">
                @include('layout.nav')
        </div>
    
        <!-- Hero content: will be in the middle -->
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">@yield('title')</h1>
                {{-- <h2 class="subtitle">Subtitle</h2> --}}
            </div>
        </div>
    </section>

    
    <div class="container is-fluid hero-body">
        @yield('content')
    </div>

    <footer class="footer">
        <div class="content has-text-centered">
            <p><strong>SmartTimes</strong> 2019</p>
        </div>
    </footer>
    {{-- <div>
            @yield('content')
    </div> --}}
    
</body>
</html>

resources/views/layout/nav.blade.php
<nav class="navbar">
    <div class="container">
        <div class="navbar-brand">
        <a class="navbar-item">
            <img src="/img/logo.png" alt="Logo">
        </a>
        <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
        </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
        <div class="navbar-end">
            <a class="navbar-item is-active" href="/">Home</a>
            <a class="navbar-item" href="/inertia">Inertia</a>
        </div>
        </div>
    </div>
</nav>